definitions:
  define.CommonFailRsp:
    properties:
      code:
        type: integer
      errmsg:
        type: string
      status:
        default: 0
        type: integer
    type: object
  define.CommonSeccessDataRsp:
    properties:
      data: {}
      status:
        default: 1
        type: integer
    type: object
  define.CommonSuccessRsp:
    properties:
      status:
        default: 1
        type: integer
    type: object
  define.GetListRsp:
    properties:
      list:
        items:
          $ref: '#/definitions/define.TodoListItem'
        type: array
      total:
        type: integer
    type: object
  define.Todo:
    properties:
      completed:
        type: boolean
      completed_at:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  define.TodoListItem:
    properties:
      completed:
        type: boolean
      id:
        type: integer
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /todo:
    post:
      description: 创建一个新的待办事项
      parameters:
      - description: 待办事项信息
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/define.Todo'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/define.CommonSuccessRsp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/define.CommonFailRsp'
      summary: 创建待办事项
      tags:
      - Todo
    put:
      description: 更新待办事项的信息
      parameters:
      - description: 待办事项信息
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/define.Todo'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/define.CommonSuccessRsp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/define.CommonFailRsp'
      summary: 更新待办事项
      tags:
      - Todo
  /todo/{id}:
    delete:
      description: 根据ID删除待办事项
      parameters:
      - description: 待办事项ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/define.CommonSuccessRsp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/define.CommonFailRsp'
      summary: 删除待办事项
      tags:
      - Todo
    get:
      description: 根据ID获取待办事项
      parameters:
      - description: 待办事项ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/define.CommonSeccessDataRsp'
            - properties:
                data:
                  $ref: '#/definitions/define.Todo'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/define.CommonFailRsp'
      summary: 获取待办事项
      tags:
      - Todo
    patch:
      description: 根据ID标记待办事项为完成
      parameters:
      - description: 待办事项ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/define.CommonSuccessRsp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/define.CommonFailRsp'
      summary: 完成待办事项
      tags:
      - Todo
  /todo/list:
    get:
      description: 获取所有待办事项的列表
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/define.CommonSeccessDataRsp'
            - properties:
                data:
                  $ref: '#/definitions/define.GetListRsp'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/define.CommonFailRsp'
      summary: 获取待办事项列表
      tags:
      - Todo
swagger: "2.0"
